name: "cron-action"
on:
  schedule:
    - cron: "*/10 * * * *" # Every 15 minutes

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i --silent && npm run start
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
